name: kadr
description: "The movie of week"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2


#--------------------PACKAGES----------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  dropdown_button2: ^2.0.0

# Utility packages
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  lottie: ^3.3.2
  url_launcher: ^6.2.0
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.1.0

# Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

# State Management
  get: ^4.6.6
  get_storage: ^2.1.1

# Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar : ^4.0.1

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.1.1


#--------------------./ PACKAGES END--------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #------------------Local assets-------------------#

  assets:
    - assets/logos/
    - assets/logos/log_logos/
    - assets/logos/appbar_logos/
    - assets/logos/splash_logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/mail_verify_images/
    - assets/images/product_images/
    - assets/images/

  #-------------------Fonts------------------------#

  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans-Black.ttf
        - asset: assets/fonts/AlbertSans-BlackItalic.ttf
        - asset: assets/fonts/AlbertSans-Bold.ttf
        - asset: assets/fonts/AlbertSans-BoldItalic.ttf
        - asset: assets/fonts/AlbertSans-ExtraBold.ttf
        - asset: assets/fonts/AlbertSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/AlbertSans-ExtraLight.ttf
        - asset: assets/fonts/AlbertSans-ExtraLightItalic.ttf
        - asset: assets/fonts/AlbertSans-Italic.ttf
        - asset: assets/fonts/AlbertSans-Light.ttf
        - asset: assets/fonts/AlbertSans-LightItalic.ttf
        - asset: assets/fonts/AlbertSans-Medium.ttf
        - asset: assets/fonts/AlbertSans-MediumItalic.ttf
        - asset: assets/fonts/AlbertSans-Regular.ttf
        - asset: assets/fonts/AlbertSans-SemiBold.ttf
        - asset: assets/fonts/AlbertSans-SemiBoldItalic.ttf
        - asset: assets/fonts/AlbertSans-Thin.ttf
        - asset: assets/fonts/AlbertSans-ThinItalic.ttf