// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9H-33cpQtNvDPrwAlYTPUKkcwp-X8xI',
    appId: '1:283060311688:web:368e26cce5fa4f1c5cf13d',
    messagingSenderId: '283060311688',
    projectId: 'kadr-ea29d',
    authDomain: 'kadr-ea29d.firebaseapp.com',
    storageBucket: 'kadr-ea29d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnaDYsvKNA8uZakV6KSTgjwPyLtP_YpyE',
    appId: '1:283060311688:android:1e166bc769d600fa5cf13d',
    messagingSenderId: '283060311688',
    projectId: 'kadr-ea29d',
    storageBucket: 'kadr-ea29d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCTHD8lZgV3ST8J3TikXUU3g6P2_9IFk',
    appId: '1:283060311688:ios:f00eb293a48574855cf13d',
    messagingSenderId: '283060311688',
    projectId: 'kadr-ea29d',
    storageBucket: 'kadr-ea29d.firebasestorage.app',
    androidClientId: '283060311688-epv10fjaocfiu2k27g0is4077tuu6drb.apps.googleusercontent.com',
    iosClientId: '283060311688-l5tr6ki3vn4harlb39mhl0gecr91jl7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.kadr',
  );

}